#!/bin/bash

#Temporary Files
FILE1=/tmp/calc1-$$
FILE2=/tmp/calc2-$$
ERROR=/tmp/calc-err-$$

which gdialog 1> /dev/null && DIALOG=gdialog || DIALOG=dialog 1> /dev/null


end () {

    rm -f $FILE1 $FILE2 $ERROR

    exit

}


#Parameters for sdn_net tool
HOST=localhost
PORT=1234

GETTEXT="gettext -d sdn_ui"

#FRONTEND


#"`$GETTEXT \"Press 1 for Encrypted Channel\"`"

#BACKEND
while true; do

	$DIALOG --inputbox "Press 1 for Encrypted Channel\nPress 2 for Quantum Encrypted Channel.\nPress 3 for Exit" 8 35 2> $FILE1 || end
	value=`cat $FILE1`
	if [ "$value" = "1" ] || [ "$value" = "2" ]
        then
 	  $DIALOG --yesno "Do you want to confirm\nthe channel conmutation ? " 8 35
          response=$?
	  case $response in
          0 )
            curl -X GET http://localhost:8080/channel/1/$value > $FILE2 && $DIALOG --infobox "Conmutation to channel $value was a success!\n `cat $FILE2` " 8 35 1> /dev/null
          ;;
	  1 )
	    break
            exit
          ;;
          esac
	elif [ "$value" = "3" ]
        then
          break
        else
	  $DIALOG --infobox "Please follow the instructions!" 8 35
        fi

	EXIT_STATUS=$?
	end
done
