#!/bin/bash

#Temporary Files
FILE1=/tmp/calc1-$$
FILE2=/tmp/calc2-$$
ERROR=/tmp/calc-err-$$

which gdialog 1> /dev/null && DIALOG=gdialog || DIALOG=dialog 1> /dev/null


end () {

    rm -f $FILE1 $FILE2 $ERROR

    exit

}


#Parameters for sdn_net tool
HOST=localhost
PORT=1234

GETTEXT="gettext -d sdn_ui"

TITLE="`$GETTEXT \"SDN CONTROLLER INTERFACE\"`"
SUBTITLE="`$GETTEXT \"Which channel you prefer for the link?\"`"
OPTION_1="`$GETTEXT \"Press 1 for Encrypted Channel\"`"
OPTION_2="`$GETTEXT \"Press 2 for Quantum Encrypted Channel\"`"
OPTION_3="`$GETTEXT \"Press 3 to Exit\"`"
CONFIRM="`$GETTEXT \"Do you want to confirm the channel switch?\"`"
ERROR="`$GETTEXT \"Please follow the instructions!\"`"
#FRONTEND


#"`$GETTEXT \"Press 1 for Encrypted Channel\"`"

#BACKEND
while true; do

	$DIALOG --title "$TITLE" --menu "$SUBTITLE" 10 60 1 1 "$OPTION_1" 2 "$OPTION_2" 3 "$OPTION_3" 2> $FILE1 || end
	value=`cat $FILE1`
	if [ "$value" = "1" ] || [ "$value" = "2" ]
        then
 	  $DIALOG --yesno "$CONFIRM" 40 40
          response=$?
	  case $response in
          0 )
            curl -X GET http://localhost:8080/channel/1/$value > $FILE2 && $DIALOG --infobox "Conmutation to channel $value was a success!\n `cat $FILE2` " 40 40 1> /dev/null
          ;;
	  1 )
	    break
            exit
          ;;
          esac
	elif [ "$value" = "3" ]
        then
          break
        else
	  $DIALOG --infobox "$ERROR" 40 40
        fi

	EXIT_STATUS=$?
	end
done
